<a href="https://colab.research.google.com/github/imraunav/Pytorch-tutorial/blob/main/1_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [1]:
import torch
import numpy as np

In [8]:
data = [[3, 4],
      [1, 2],]
x_data = torch.tensor(data)
x_data

tensor([[3, 4],
        [1, 2]])

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[3, 4],
        [1, 2]])

In [9]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4393, 0.0234],
        [0.0022, 0.3864]]) 



In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2594, 0.3181, 0.3100],
        [0.8356, 0.7853, 0.0895]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
tensor = torch.rand(3,4)

print(f"Shape of a tensor: {tensor.shape}")
print(f"Datatype of a tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of a tensor: torch.Size([3, 4])
Datatype of a tensor: torch.float32
Device tensor is stored on: cpu


In [12]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [14]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
tensor[..., -1] = 2
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.]])


In [18]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.]])


In [19]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 4.],
        [1., 0., 1., 4.],
        [1., 0., 1., 4.],
        [1., 0., 1., 4.]])

In [20]:
y1, y2, y3

(tensor([[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]),
 tensor([[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]),
 tensor([[6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.],
         [6., 6., 6., 6.]]))

In [21]:
z1, z2, z3

(tensor([[1., 0., 1., 4.],
         [1., 0., 1., 4.],
         [1., 0., 1., 4.],
         [1., 0., 1., 4.]]),
 tensor([[1., 0., 1., 4.],
         [1., 0., 1., 4.],
         [1., 0., 1., 4.],
         [1., 0., 1., 4.]]),
 tensor([[1., 0., 1., 4.],
         [1., 0., 1., 4.],
         [1., 0., 1., 4.],
         [1., 0., 1., 4.]]))

In [22]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

16.0 <class 'float'>


In [23]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.],
        [1., 0., 1., 2.]]) 

tensor([[6., 5., 6., 7.],
        [6., 5., 6., 7.],
        [6., 5., 6., 7.],
        [6., 5., 6., 7.]])


In [24]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [25]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [26]:
n = np.ones(5)
t = torch.from_numpy(n)

In [27]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
